[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "auralis"
version = "0.1.0"
description = "Lightweight local real-time audio classification"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26",
    "onnxruntime>=1.18",
    "librosa>=0.10",
    "sounddevice>=0.5",
    "soundfile>=0.12"
]

[tool.setuptools.packages.find]
include = ["auralis*"]

[tool.setuptools.package-data]
"auralis" = ["model/*.onnx", "model/*.json"]
